### ISSUE TITLE
Only shows loading

### ISSUE THREAD

**Issue by dimike96** [fajtak/ulauncher-weather#1]
If I open uLauncher and use the w keyword all I see is the weather icon followed by "Loading...". Is this an issue with my openweather key? I have directly copied and pasted a couple different keys with no success.

**Comment by fajtak** [comment]
Hi,

in my case it took the key about hour or two to be "activated" by the OpenWeatherMap administrators. Can you try it now?

Thank a let me know
Lukas

**Comment by dimike96** [comment]
Thanks for the quick response! That's all it was, I failed to read about the delay on OpenWeatherMap's site. Works great! Thanks for the work on this!

**Comment by fajtak** [comment]
Sure, no problem. Glad that you like it. If you don't mind, give me a star
on github.

Thanks a lot
Lukas

**Comment by fajtak** [comment]
BTW, I just pushed a new version with OpenWeatherMap.org redirecting and
better Readme. Let me know if you have any ideas/suggestions that you would
like to see or use.

Thanks
Lukas

**Comment by luisaureliocasoni** [comment]
One tip for all users. Check if the key pasted has spaces before and after the token. I have pasted the key with additional spaces before the token, then the plugin stucks on load. I removed the additional spaces and works!

Thanks for developer to this plugin.

**Comment by fajtak** [comment]
Thanks a lot for this tip. It can help someone. Just for your information I just pushed a new version. When you search an individual city "w Prague" you will get much more infromation like precipitation in the next hour in the newxt 12 hours and forecast for the next three days. If you like it, please give me a star. Thanks.
